name: Github release

on:
    push:
      # branches to consider in the event; optional, defaults to all
      branches:
        - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
      
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<jchhun-FP+1@familyproud.com>"
      
      - name: Bump version
        uses: qzb/standard-version-action@v1.0.5
      
      - name: Push git tags
        run: git push --follow-tags origin          

